import { mkdirSync, readFileSync, copyFileSync, existsSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { root,json,run,snapshot } from './lab-evidence.mjs';
const out=path.join(root,'spikes/a-spec-kit-manifest/evidence/rig-baseline');
const cwd=path.join(root,'.lab-runs/baseline-090');
mkdirSync(out,{recursive:true}); mkdirSync(cwd,{recursive:true});
const metadata=run('npm',['view','create-agent-rig@0.9.0','name','version','dist','--json'],cwd,out+'/registry-command.json');
assert.equal(metadata.exitCode,0);
const pkg=JSON.parse(metadata.stdout);
const tarPath=path.join(root,'.lab-runs/registry-090/create-agent-rig-0.9.0.tgz');
if(!existsSync(tarPath)) { mkdirSync(path.dirname(tarPath),{recursive:true}); const r=await fetch(pkg.dist.tarball); assert(r.ok); writeFileSync(tarPath,Buffer.from(await r.arrayBuffer())); }
const tar=readFileSync(tarPath);
assert.equal('sha512-'+createHash('sha512').update(tar).digest('base64'),pkg.dist.integrity);
json(out+'/provenance.json',{package:pkg,verifiedIntegrity:pkg.dist.integrity,node:process.version,npm:run('npm',['--version'],cwd).stdout.trim(),os:{platform:os.platform(),release:os.release(),arch:os.arch()},scenarioSha:run('git',['rev-parse','HEAD'],root).stdout.trim(),scenarioScriptSha256:createHash('sha256').update(readFileSync(import.meta.filename)).digest('hex'),checkedAt:new Date().toISOString()});
for(const [name,args] of [['version',['--version']],['help',['--help']],['init-help',['init','--help']],['upgrade-help',['upgrade','--help']],['handshake',['--version','--json']]]) run('npx',['--yes','create-agent-rig@0.9.0',...args],cwd,out+'/'+name+'.json');
run('git',['init'],cwd,out+'/git-init.json');
run('git',['-c','user.name=Lab Fixture','-c','user.email=lab@example.invalid','commit','--allow-empty','-m','synthetic baseline'],cwd);
snapshot(cwd,out+'/before-init.json');
const init=run('npx',['--yes','create-agent-rig@0.9.0','init'],cwd,out+'/init.json');
run('git',['add','--intent-to-add','.'],cwd,out+'/git-intent-to-add.json');
const after=snapshot(cwd,out+'/after-init.json');
for(const p of Object.keys(after.files).filter(p=>/manifest.*\.json$/.test(p))) copyFileSync(path.join(cwd,p),path.join(out,'manifest-'+p.replaceAll('/','__')));
json(out+'/summary.json',{initExitCode:init.exitCode,installationMs:init.durationMs,payloadFiles:after.count,payloadBytes:after.bytes,manifestPaths:Object.keys(after.files).filter(p=>/manifest.*\.json$/.test(p))});
console.log(JSON.stringify({exit:init.exitCode,files:after.count,bytes:after.bytes}));
