import {mkdirSync,readFileSync,writeFileSync,appendFileSync,existsSync,unlinkSync} from 'node:fs';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
import {root,json,run,snapshot,sha} from './lab-evidence.mjs';
const out=path.join(root,'spikes/f-native-projection/evidence/ruler');
const install=path.join(root,'.lab-runs/f-ruler-package');
mkdirSync(out,{recursive:true});mkdirSync(install,{recursive:true});
const version='0.3.44', commit='658d1bc168e3496015aa5c262361cce818fabcf9';
const registry=await (await fetch('https://registry.npmjs.org/@intellectronica%2fruler')).json();
const pkg=registry.versions[version];assert.equal(pkg.gitHead,commit);
const bytes=Buffer.from(await (await fetch(pkg.dist.tarball)).arrayBuffer());
assert.equal('sha512-'+createHash('sha512').update(bytes).digest('base64'),pkg.dist.integrity);
writeFileSync(path.join(install,'ruler.tgz'),bytes);
json(out+'/provenance.json',{checkedAt:new Date().toISOString(),version,commit,license:pkg.license,dist:pkg.dist,latest:registry['dist-tags'].latest,releasedAt:registry.time[version],node:process.version,platform:process.platform,scenarioSha:run('git',['rev-parse','HEAD'],root).stdout.trim(),scriptSha256:sha(readFileSync(import.meta.filename)),source:'https://github.com/intellectronica/ruler/tree/'+commit});
writeFileSync(path.join(install,'package.json'),JSON.stringify({private:true,name:'synthetic-ruler-lab',version:'0.0.0'}));
const dep=run('npm',['install','--ignore-scripts','--no-audit','--no-fund','--save-exact','./ruler.tgz'],install,out+'/install-command.json');assert.equal(dep.exitCode,0);
json(out+'/dependency-lock.json',JSON.parse(readFileSync(path.join(install,'package-lock.json'))));
const rulerCli=path.join(install,'node_modules/@intellectronica/ruler/dist/cli/index.js');
const rigMeta=await (await fetch('https://registry.npmjs.org/create-agent-rig/0.9.0')).json();
const rigTar=path.join(install,'rig.tgz');
const cached=path.join(root,'.lab-runs/registry-090/create-agent-rig-0.9.0.tgz');
const rigBytes=existsSync(cached)?readFileSync(cached):Buffer.from(await (await fetch(rigMeta.dist.tarball)).arrayBuffer());
assert.equal('sha512-'+createHash('sha512').update(rigBytes).digest('base64'),rigMeta.dist.integrity);writeFileSync(rigTar,rigBytes);
assert.equal(run('tar',['-xzf',rigTar,'-C',install],root,out+'/extract-rig.json').exitCode,0);
const rigPkg=JSON.parse(readFileSync(path.join(install,'package/package.json')));
const rigCli=path.join(install,'package',typeof rigPkg.bin==='string'?rigPkg.bin:Object.values(rigPkg.bin)[0]);
json(out+'/rig-provenance.json',{version:rigMeta.version,dist:rigMeta.dist,verifiedIntegrity:rigMeta.dist.integrity});
for(const [name,args] of [['help',['--help']],['version',['--version']],['init-help',['init','--help']],['apply-help',['apply','--help']],['revert-help',['revert','--help']]]) {const r=run('node',[rulerCli,...args],install,out+'/'+name+'.json');assert.equal(r.exitCode,0);}
for(const [name,args] of [['rig-help',['--help']],['rig-init-help',['init','--help']],['rig-upgrade-help',['upgrade','--help']]]) run('node',[rigCli,...args],install,out+'/'+name+'.json');
const results=[];
for(const order of ['rig-first','ruler-first']) {
 const cwd=path.join(root,'.lab-runs/f-ruler-'+order);assert(!existsSync(cwd),'fresh fixture required: '+cwd);mkdirSync(cwd,{recursive:true});
 const evidence=out+'/'+order;let n=0;
 const snap=name=>snapshot(cwd,evidence+`/${String(n++).padStart(2,'0')}-${name}.json`);
 const cmd=(name,cli,args)=>{const r=run('node',[cli,...args],cwd,evidence+`/${String(n++).padStart(2,'0')}-${name}-command.json`);snap(name);return r;};
 const rig=(name,args)=>cmd(name,rigCli,args);
 const ruler=(name,args)=>cmd(name,rulerCli,args);
 const apply=name=>ruler(name,['apply','--agents','claude,codex','--local-only','--no-mcp','--no-gitignore','--subagents']);
 const seed=()=>{assert.equal(ruler('ruler-init',['init']).exitCode,0);writeFileSync(path.join(cwd,'.ruler/AGENTS.md'),'# Synthetic shared rules\nUse deterministic fixtures.\n');mkdirSync(path.join(cwd,'.ruler/skills/lab-skill'),{recursive:true});writeFileSync(path.join(cwd,'.ruler/skills/lab-skill/SKILL.md'),'---\nname: lab-skill\ndescription: Synthetic fixture skill\n---\nVerify synthetic fixtures.\n');mkdirSync(path.join(cwd,'.ruler/agents'),{recursive:true});writeFileSync(path.join(cwd,'.ruler/agents/lab-reviewer.md'),'---\nname: lab-reviewer\ndescription: Synthetic read-only reviewer\nreadonly: true\nmodel: inherit\neffort: high\n---\nReview only synthetic files.\n');return apply('ruler-first-apply');};
 run('git',['init'],cwd);run('git',['-c','user.name=Lab Fixture','-c','user.email=lab@example.invalid','commit','--allow-empty','-m','synthetic'],cwd);
 assert.equal((order==='rig-first'?rig('rig-init',['init']):seed()).exitCode,0);const first=snap('first');
 const secondCommand=order==='rig-first'?seed():rig('rig-init',['init']);const second=snap('second');
 if(secondCommand.exitCode!==0){results.push({order,blocked:true,secondComponentExit:secondCommand.exitCode,reason:secondCommand.stderr||secondCommand.stdout,filesUnchangedByRefusal:JSON.stringify(first.files)===JSON.stringify(second.files)});continue;}
 const manifest=JSON.parse(readFileSync(path.join(cwd,'.claude/.rig-manifest.json')));
 json(evidence+'/ownership.json',Object.fromEntries(Object.entries(second.files).map(([p,f])=>[p,{...f,rigClaims:p in manifest.files,rulerSource:p.startsWith('.ruler/'),createdBySecond:!(p in first.files),changedBySecond:p in first.files&&f.sha256!==first.files[p].sha256}])));
 const repeatRig=rig('rig-repeat-init',['init']);const repeatRuler=ruler('ruler-repeat-init',['init']);
 const beforeRepeat=snap('before-repeat');const repeatApply=apply('ruler-repeat-apply');const afterRepeat=snap('after-repeat');
 const stableBefore=snap('stable-before');const stableApply=apply('stable-apply');const stableAfter=snap('stable-after');
 const dryBefore=snap('dry-before');const dry=rig('rig-dry',['upgrade','--dry-run']);const dryAfter=snap('dry-after');
 run('git',['add','-f','.'],cwd);run('git',['-c','user.name=Lab Fixture','-c','user.email=lab@example.invalid','commit','-m','combined'],cwd);
 for(const p of ['AGENTS.md','CLAUDE.md'])appendFileSync(path.join(cwd,p),'\nSynthetic user override KEEP-ME.\n');
 const settings=path.join(cwd,'.claude/settings.json');const settingsData=JSON.parse(readFileSync(settings));settingsData.labSyntheticOverride=true;writeFileSync(settings,JSON.stringify(settingsData,null,2)+'\n');
 const deleted='.claude/rules/autonomy.md';unlinkSync(path.join(cwd,deleted));const edited=snap('edited');
 const rigUpgrade=rig('rig-upgrade-edited',['upgrade','--yes']);const afterRig=snap('after-rig');
 const projected='.claude/skills/lab-skill/SKILL.md';appendFileSync(path.join(cwd,projected),'\nSynthetic skill edit KEEP-SKILL.\n');
 appendFileSync(path.join(cwd,'.ruler/AGENTS.md'),'\nSynthetic canonical v2.\n');
 const rulerDryBefore=snap('ruler-dry-before');const rulerDry=ruler('ruler-dry',['apply','--agents','claude,codex','--local-only','--no-mcp','--no-gitignore','--subagents','--dry-run']);const rulerDryAfter=snap('ruler-dry-after');
 const rulerUpgrade=apply('ruler-source-update');const afterRuler=snap('after-ruler');
 const sourceUpdatePropagated=readFileSync(path.join(cwd,'CLAUDE.md'),'utf8').includes('canonical v2');
 json(evidence+'/shared-user-edit-markers.json',Object.fromEntries(['AGENTS.md','CLAUDE.md'].map(p=>[p,{userEditPresent:readFileSync(path.join(cwd,p),'utf8').includes('KEEP-ME'),sourceUpdatePresent:readFileSync(path.join(cwd,p),'utf8').includes('canonical v2')}])));
 const generatedEditPreserved=readFileSync(path.join(cwd,projected),'utf8').includes('KEEP-SKILL');
 unlinkSync(path.join(cwd,projected));snap('projected-delete');apply('ruler-after-delete');const projectedDeletePreserved=!existsSync(path.join(cwd,projected));
 const preRevert=snap('before-revert');const revert=ruler('ruler-revert',['revert','--agents','claude,codex','--local-only']);const postRevert=snap('after-revert');
 const survivingRig=rig('rig-after-revert-dry',['upgrade','--dry-run']);
 const agentPaths=['.claude/agents/lab-reviewer.md','.codex/agents/lab-reviewer.toml'];
 json(evidence+'/agent-projections.json',Object.fromEntries(agentPaths.map(p=>[p,existsSync(path.join(cwd,p))?readFileSync(path.join(cwd,p),'utf8'):null])));
 results.push({order,repeatRigExit:repeatRig.exitCode,repeatRulerExit:repeatRuler.exitCode,repeatApplyExit:repeatApply.exitCode,immediateRepeatIdentical:JSON.stringify(beforeRepeat.files)===JSON.stringify(afterRepeat.files),stableRepeatIdentical:JSON.stringify(stableBefore.files)===JSON.stringify(stableAfter.files),rigDryExit:dry.exitCode,rigDryReadOnly:JSON.stringify(dryBefore.files)===JSON.stringify(dryAfter.files),rigUpgradeExit:rigUpgrade.exitCode,rigPreservesUserEdits:['AGENTS.md','CLAUDE.md','.claude/settings.json'].every(p=>edited.files[p].sha256===afterRig.files[p]?.sha256),rigDeletedStaysRemoved:!afterRig.files[deleted],rulerDryExit:rulerDry.exitCode,rulerDryReadOnly:JSON.stringify(rulerDryBefore.files)===JSON.stringify(rulerDryAfter.files),rulerUpgradeExit:rulerUpgrade.exitCode,sourceUpdatePropagated,generatedEditPreserved,projectedDeletePreserved,rulerPreservesSharedEdits:['AGENTS.md','CLAUDE.md'].map(p=>({path:p,preserved:afterRuler.files[p]?.sha256===afterRig.files[p]?.sha256})),rulerRevertExit:revert.exitCode,rigDryAfterRevertExit:survivingRig.exitCode,rigFilesChangedByRevert:Object.keys(manifest.files).filter(p=>preRevert.files[p]&&preRevert.files[p].sha256!==postRevert.files[p]?.sha256),remainingProjectedAgents:agentPaths.filter(p=>existsSync(path.join(cwd,p))),secondOverwrites:Object.keys(first.files).filter(p=>second.files[p]?.sha256!==first.files[p].sha256),rigUninstall:'unverified: no native command in 0.9.0',releaseUpgrade:'unverified: source update/reapply only; same package version'});
 results.at(-1).stableRepeatExit=stableApply.exitCode;
}
json(out+'/results.json',results);console.log(JSON.stringify(results,null,2));
assert(results.every(r=>r.blocked||r.repeatApplyExit===0&&r.rigDryExit===0&&r.rigUpgradeExit===0&&r.rulerUpgradeExit===0&&r.rulerRevertExit===0));
