import {mkdirSync,readFileSync,writeFileSync,cpSync,existsSync,readdirSync,renameSync} from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {root,run,json,snapshot,sha} from './lab-evidence.mjs';
import {McpProbe,mcpText} from './lab-mcp-probe.mjs';
const out='spikes/e-memory/evidence/basic',base=path.join(root,'.lab-runs/e-basic-'+Date.now()),home=path.join(base,'home'),notes=path.join(base,'notes'),config=path.join(base,'config');mkdirSync(home,{recursive:true});mkdirSync(notes,{recursive:true});
const cli=path.join(root,'.lab-runs/e-basic-tools/venv',process.platform==='win32'?'Scripts/bm.exe':'bin/bm');
const env={HOME:home,USERPROFILE:home,BASIC_MEMORY_CONFIG_DIR:config,BASIC_MEMORY_HOME:path.join(notes,'default'),BASIC_MEMORY_AUTO_UPDATE:'false',BASIC_MEMORY_FORCE_LOCAL:'true',BASIC_MEMORY_SEMANTIC_SEARCH_ENABLED:'false',BASIC_MEMORY_LOGFIRE_SEND_TO_LOGFIRE:'false',BASIC_MEMORY_LOG_LEVEL:'ERROR',PYTHONUTF8:'1',PYTHONIOENCODING:'utf-8',HF_HUB_OFFLINE:'1',XDG_CONFIG_HOME:path.join(home,'.config'),XDG_CACHE_HOME:path.join(home,'.cache')};
for(const k of Object.keys(process.env))if(/TOKEN|SECRET|PASSWORD|API_KEY|AUTH|^BASIC_MEMORY_|^ANTHROPIC_|^OPENAI_/i.test(k)&&!(k in env))env[k]='';
let n=0;const command=(label,args)=>{const r=run(cli,args,base,out+`/${n++}-${label}.json`,env);assert.equal(r.exitCode,0,r.stderr);return r;};
assert.equal(run('git',['init','-q'],base).exitCode,0);assert.equal(run('git',['-c','user.name=Synthetic Lab','-c','user.email=lab@example.invalid','commit','--allow-empty','-m','synthetic'],base).exitCode,0);
command('version',['--version']);command('project-add-help',['project','add','--help']);
for(const p of ['alpha','beta'])command('project-'+p,['project','add',p,path.join(notes,p),'--local']);
const checkoutA=path.join(base,'checkout-a'),checkoutB=path.join(base,'checkout-b');for(const [name,cwd]of [['a',checkoutA],['b',checkoutB]])assert.equal(run('git',['worktree','add','-q','-b','synthetic-'+name,cwd,'HEAD'],base,out+'/worktree-'+name+'.json').exitCode,0);
const live=[];async function connect(label,project,cwd=base){const p=new McpProbe(cli,['mcp',...(project?['--project',project]:[])],cwd,env,out+'/'+label+'-protocol.json');live.push(p);const initialize=await p.start();json(out+'/'+label+'-initialize.json',initialize);return p;}
const result={version:'0.23.2',sourceCommit:'c0bd87c6d5a4a58034b1d6c8c5018e443b0bd048',license:'AGPL-3.0-or-later',scenarioSha:run('git',['rev-parse','HEAD'],root).stdout.trim(),scriptSha256:sha(readFileSync(import.meta.filename)),runDirectory:path.relative(root,base),node:process.version,platform:process.platform,checks:[],claimBoundary:'Direct independent MCP clients, not native model memory extraction or model recall.'};
const check=(name,value,detail)=>result.checks.push({name,passed:!!value,detail});
async function tool(p,name,args,label){const value=await p.tool(name,args);json(out+'/'+label+'.json',value);p.save();return value;}
function payload(value){if(value?.structuredContent&&typeof value.structuredContent==='object')return value.structuredContent.result??value.structuredContent;try{return JSON.parse(mcpText(value));}catch{return {};}}
try{
 const a=await connect('client-a',undefined,checkoutA);const schema=await a.request('tools/list');json(out+'/tools.json',schema);assert(schema.result.tools.some(x=>x.name==='write_note'));assert(schema.result.tools.some(x=>x.name==='read_note'));
 if(process.argv.includes('--discover')){json(out+'/discovery.json',{base:path.relative(root,base),tools:schema.result.tools.map(x=>x.name)});}else{
 const seeds=[['alpha','Orchid deploy','ORCHID_ALPHA_DEPLOY: use port 4101.'],['alpha','Orchid tests','ORCHID_ALPHA_TESTS: run synthetic tests.'],['alpha','Garden','BASIL_ALPHA: unrelated gardening.'],['beta','Orchid deploy','ORCHID_BETA_PRIVATE: use port 9109.']];
 const seedPaths={},expectedPermalinks=[];for(const [project,title,content]of seeds){const r=await tool(a,'write_note',{project,title,content,directory:'notes',output_format:'json'},'seed-'+project+'-'+title.replaceAll(' ','-')),data=payload(r);check('write '+project+' '+title,!r.isError&&data.action==='created');seedPaths[project+'/'+title]=data.file_path;if(project==='alpha'&&title.startsWith('Orchid')&&data.permalink)expectedPermalinks.push(data.permalink);}
 const b=await connect('client-b',undefined,checkoutB);
 const readA=await tool(b,'read_note',{project:'alpha',identifier:'notes/orchid-deploy'},'cross-client-read');check('shared memory visible to independent new process and worktree',mcpText(readA).includes('ORCHID_ALPHA_DEPLOY'));
 const readB=await tool(a,'read_note',{project:'beta',identifier:'notes/orchid-deploy'},'beta-read');check('explicit project separation',mcpText(readB).includes('ORCHID_BETA_PRIVATE')&&!mcpText(readB).includes('ORCHID_ALPHA_DEPLOY'));
 const query=await tool(b,'search_notes',{project:'alpha',query:'ORCHID',search_type:'text',output_format:'json'},'retrieval'),queryData=payload(query),returned=[...new Set((queryData.results||[]).map(x=>x.permalink))],correct=returned.filter(x=>expectedPermalinks.includes(x)).length;check('search returns exactly expected alpha notes',!query.isError&&expectedPermalinks.length===2&&returned.length===2&&correct===2);json(out+'/retrieval-measurement.json',{responseBytes:Buffer.byteLength(JSON.stringify(query)),query:'ORCHID',expectedPermalinks,returnedPermalinks:returned,precision:returned.length?correct/returned.length:null,recall:expectedPermalinks.length?correct/expectedPermalinks.length:null,rawResponse:'retrieval.json',semanticSearchEnabled:false});
 const locked=await connect('alpha-constrained','alpha');const healthy=await tool(locked,'read_note',{project:'alpha',identifier:'notes/orchid-deploy'},'constrained-alpha-read');const wrong=await tool(locked,'read_note',{project:'beta',identifier:'notes/orchid-deploy'},'constrained-wrong-project');check('constrained server prevents beta read',!healthy.isError&&mcpText(healthy).includes('ORCHID_ALPHA_DEPLOY')&&!mcpText(wrong).includes('ORCHID_BETA_PRIVATE')&&(mcpText(wrong).includes('ORCHID_ALPHA_DEPLOY')||/restricted|constrained|not allowed|cannot access/i.test(mcpText(wrong))));await locked.close();
 const traversal=await tool(a,'write_note',{project:'alpha',title:'Escape',directory:'../../escape',content:'SYNTHETIC_ESCAPE'},'path-traversal');check('path traversal rejected',traversal.isError||/error|invalid|outside|not allowed|traversal/i.test(mcpText(traversal)));check('no escaped note created',!existsSync(path.join(base,'escape/escape.md')));
 const secret=await tool(a,'write_note',{project:'alpha',title:'Synthetic canary',directory:'notes',content:'SYNTHETIC_NOT_A_CREDENTIAL_12345'},'canary-write');const canary=await tool(b,'read_note',{project:'alpha',identifier:'notes/synthetic-canary'},'canary-read');check('canary write/read probe succeeds',!secret.isError&&!canary.isError&&mcpText(canary).includes('SYNTHETIC_NOT_A_CREDENTIAL_12345'));check('memory automatically redacts supplied canary',!secret.isError&&!canary.isError&&mcpText(canary).includes('Synthetic canary')&&!mcpText(canary).includes('SYNTHETIC_NOT_A_CREDENTIAL_12345'),'Plaintext canary is synthetic; this is not a detector benchmark for valid credential formats.');
 const writes=[];for(let i=0;i<8;i++)writes.push(tool(i%2?a:b,'write_note',{project:'alpha',title:'Concurrent '+i,directory:'concurrent',content:'CONCURRENT_'+i},'concurrent-'+i));const concurrent=await Promise.all(writes);check('concurrent independent-note writes all acknowledge',concurrent.every(x=>!x.isError));
 for(let i=0;i<8;i++){const r=await tool(a,'read_note',{project:'alpha',identifier:'concurrent/concurrent-'+i},'concurrent-read-'+i);check('concurrent note '+i+' survives',mcpText(r).includes('CONCURRENT_'+i));}
 await tool(a,'write_note',{project:'alpha',title:'Shared append',directory:'notes',content:'BASE'},'append-seed');const append=await Promise.all([tool(a,'edit_note',{project:'alpha',identifier:'notes/shared-append',operation:'append',content:'WRITER_A'},'append-a'),tool(b,'edit_note',{project:'alpha',identifier:'notes/shared-append',operation:'append',content:'WRITER_B'},'append-b')]);const appended=await tool(a,'read_note',{project:'alpha',identifier:'notes/shared-append'},'append-read');check('concurrent same-note appends both survive',mcpText(appended).includes('WRITER_A')&&mcpText(appended).includes('WRITER_B'),{acknowledged:append.map(x=>!x.isError)});
 await a.close();await b.close();
 const backup=path.join(base,'backup');cpSync(notes,backup,{recursive:true});const before=snapshot(base,out+'/before-restart-snapshot.json',env);const c=await connect('restart');const restart=await tool(c,'read_note',{project:'alpha',identifier:'notes/orchid-deploy'},'restart-read');check('restart persists note',mcpText(restart).includes('ORCHID_ALPHA_DEPLOY'));
 const garden=path.join(notes,'alpha',seedPaths['alpha/Garden']);assert(existsSync(garden));const del=await tool(c,'delete_note',{project:'alpha',identifier:'notes/garden',output_format:'json'},'delete-note');const deleted=await tool(c,'read_note',{project:'alpha',identifier:'notes/garden'},'read-deleted'),neighbor=await tool(c,'read_note',{project:'alpha',identifier:'notes/orchid-deploy'},'deletion-surviving-neighbor');check('native note deletion',!del.isError&&payload(del).deleted===true&&!existsSync(garden)&&/Note Not Found/i.test(mcpText(deleted))&&!neighbor.isError&&mcpText(neighbor).includes('ORCHID_ALPHA_DEPLOY'));await c.close();
 json(out+'/backup.json',{copiedSyntheticMarkdown:true,backupPath:path.relative(base,backup),configPath:path.relative(base,config),files:before.count});
 const importFile=path.join(backup,'alpha',seedPaths['alpha/Orchid deploy']);assert(path.resolve(importFile).startsWith(backup+path.sep));writeFileSync(importFile,readFileSync(importFile,'utf8')+'\nIMPORT_COPY_ONLY\n');
 command('import-markdown-project',['project','add','imported',path.join(backup,'alpha'),'--local']);command('reindex-help',['reindex','--help']);command('reindex-import',['reindex','--project','imported','--full','--search']);
 const imported=await connect('imported');const shortImported=await tool(imported,'read_note',{project:'imported',identifier:'notes/orchid-deploy'},'imported-short-read');check('short permalink remains valid after project rename',!shortImported.isError&&mcpText(shortImported).includes('IMPORT_COPY_ONLY'));
 const importedNote=await tool(imported,'read_note',{project:'imported',identifier:seedPaths['alpha/Orchid deploy']},'imported-file-read');check('Markdown export/import preserves content using file identity',!importedNote.isError&&mcpText(importedNote).includes('ORCHID_ALPHA_DEPLOY')&&mcpText(importedNote).includes('IMPORT_COPY_ONLY'));await imported.close();
 // Back up only this isolated config, then corrupt its synthetic SQLite file.
 const configBackup=path.join(base,'config-backup'),quarantine=path.join(base,'corrupt-config');cpSync(config,configBackup,{recursive:true});const database=path.join(config,'memory.db');assert(path.resolve(database).startsWith(base+path.sep));assert(existsSync(database));assert(readFileSync(database).subarray(0,15).toString()==='SQLite format 3');writeFileSync(database,'SYNTHETIC_CORRUPT_SQLITE');
 let corruptDiagnostic='';try{const corrupt=await connect('corrupt');const r=await tool(corrupt,'read_note',{project:'alpha',identifier:'notes/orchid-deploy'},'corrupt-read');corruptDiagnostic=JSON.stringify(r)+'\n'+corrupt.stderr;await corrupt.close();}catch(error){corruptDiagnostic=error.message+'\n'+live.at(-1).stderr;}finally{for(const p of live)await p.close();}
 const corruptError=/file is not a database|database disk image is malformed|sqlite.*corrupt|database.*corrupt/i.test(corruptDiagnostic);json(out+'/corruption-error.json',{diagnostic:corruptDiagnostic,classifiedAsDatabaseCorruption:corruptError,expectedFault:'synthetic invalid SQLite file'});check('corruption surfaces a classified database error',corruptError);assert(path.resolve(config).startsWith(base+path.sep)&&path.resolve(quarantine).startsWith(base+path.sep));renameSync(config,quarantine);cpSync(configBackup,config,{recursive:true});
 const restored=await connect('restored');const restore=await tool(restored,'read_note',{project:'alpha',identifier:'notes/orchid-deploy'},'restore-read');check('backup restores readable notes',mcpText(restore).includes('ORCHID_ALPHA_DEPLOY'));await restored.close();
 command('doctor-help',['doctor','--help']);const doctor=run(cli,['doctor'],base,out+'/doctor.json',env);check('native doctor completes',doctor.exitCode===0);
 if(process.platform==='linux'){const offline=new McpProbe('sudo',['unshare','-n','--','env',...Object.entries(env).map(([k,v])=>k+'='+v),cli,'mcp','--project','alpha'],base,env,out+'/offline-protocol.json');live.push(offline);try{await offline.start();const r=await tool(offline,'read_note',{identifier:'notes/orchid-deploy'},'offline-read');check('network namespace offline read',mcpText(r).includes('ORCHID_ALPHA_DEPLOY'));}finally{await offline.close();}}
 snapshot(base,out+'/final-snapshot.json',env);
 }
}finally{for(const p of live)await p.close();json(out+'/result.json',result);}
console.log(JSON.stringify({checks:result.checks.length,failed:result.checks.filter(x=>!x.passed).map(x=>x.name)}));
