// Authorized private lab only. Real board/ref/worktree/PR calls; no model inference.
import {spawn} from 'node:child_process';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {root,run,json,sha,snapshot} from './lab-evidence.mjs';
const repository='serhii-baksheiev/agent-stack-lab',apiRoot='repos/'+repository,stamp=Date.now(),base=path.join(root,'.lab-runs/d-board-'+stamp),out='spikes/d-team-orchestration/evidence/board';mkdirSync(base,{recursive:true});
const checks=[],issues=[],prs=[],branches=[],add=(name,passed,detail)=>checks.push({name,passed,detail});let sequence=0;
async function api(label,method,endpoint,body,headers=[]){
 assert(endpoint===apiRoot||endpoint.startsWith(apiRoot+'/'),'Only laboratory API endpoints');
 const args=['api',endpoint,'--method',method,'--include','-H','Accept: application/vnd.github+json','-H','X-GitHub-Api-Version: 2026-03-10',...headers.flatMap(x=>['-H',x])];if(body!==undefined)args.push('--input','-');
 const startedAt=new Date().toISOString(),start=Date.now();const response=await new Promise((resolve,reject)=>{const child=spawn('gh',args,{cwd:root,stdio:['pipe','pipe','pipe'],windowsHide:true});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.on('error',reject);const timer=setTimeout(()=>child.kill(),60000);child.on('close',code=>{clearTimeout(timer);resolve({code,stdout,stderr});});child.stdin.end(body===undefined?'':JSON.stringify(body));});
 const split=response.stdout.search(/\r?\n\r?\n/),head=split<0?'':response.stdout.slice(0,split),raw=split<0?response.stdout:response.stdout.slice(split).trim();let data;try{data=JSON.parse(raw);}catch{data=raw;}
 const status=Number(head.match(/^HTTP\/\S+\s+(\d+)/m)?.[1]),record={label,method,endpoint,request:body,requestHeaders:headers,startedAt,durationMs:Date.now()-start,exitCode:response.code,status,responseHeaders:head,data,stderr:response.stderr};json(out+`/api/${sequence++}-${label}.json`,record);return record;
}
function ok(r,codes=[200,201,204]){assert(codes.includes(r.status),JSON.stringify({label:r.label,status:r.status,error:r.data}));return r.data;}
const get=(label,endpoint)=>api(label,'GET',endpoint+(endpoint.includes('?')?'&':'?')+'lab_probe='+Date.now());
function save(){json(out+'/result.json',{repository,stamp,scriptSha256:sha(readFileSync(import.meta.filename)),scenarioSha:run('git',['rev-parse','HEAD'],root).stdout.trim(),platform:process.platform,node:process.version,checks,issues:issues.map(x=>({number:x.number,id:x.id,url:x.html_url})),prs,branches,scope:'Two synthetic process actors using one authorized lab account; not two model inference sessions or independent GitHub identities.'});}
function command(label,args,cwd=base){const r=run('git',args,cwd,out+'/git/'+label+'.json');assert.equal(r.exitCode,0,r.stderr);return r;}
const gitAuth=['-c','credential.helper=','-c','credential.helper=!gh auth git-credential'];
try{
 const repo=ok(await get('privacy',apiRoot));assert(repo.private===true);assert.equal(repo.full_name,repository);add('private repository verified',true);
 for(const [id,title]of [['D-T1','Implement counter'],['D-T2','Validate counter'],['D-T3','Document counter']]){const issue=ok(await api('create-'+id,'POST',apiRoot+'/issues',{title:`[synthetic D ${stamp}] ${id} ${title}`,body:`Synthetic feature d-counter-${stamp}. Requirement D-R1/R2/R3. Stable task identity ${repository}:d-counter-${stamp}:${id}. No production task.`}));issues.push(issue);save();}
 add('spec decomposed into three real board issues',issues.length===3);
 ok(await api('real-blocker-add','POST',apiRoot+`/issues/${issues[1].number}/dependencies/blocked_by`,{issue_id:issues[0].id}));const blockers=ok(await get('real-blocker-read',apiRoot+`/issues/${issues[1].number}/dependencies/blocked_by`));add('real blocker links prevent selecting blocked task',blockers.some(x=>x.id===issues[0].id&&x.state==='open'),{labelsUsed:false,blockedIssue:issues[1].number});
 const claimIssue=issues[2],before=await get('issue-before-race',apiRoot+`/issues/${claimIssue.number}`),etag=before.responseHeaders.match(/^Etag:\s*(.+)$/mi)?.[1]?.trim();assert(etag,'Actual issue response needs ETag');
 const claimBodies=['actor-a','actor-b'].map(actor=>({body:claimIssue.body+`\n\nSynthetic claim owner=${actor}; event=issue-etag-race; expires=${Date.now()+30000}`}));
 const race=await Promise.all(claimBodies.map((body,i)=>api('issue-claim-'+i,'PATCH',apiRoot+`/issues/${claimIssue.number}`,body,['If-Match: '+etag])));const after=ok(await get('issue-after-race',apiRoot+`/issues/${claimIssue.number}`));
 add('issue If-Match admits exactly one concurrent owner',race.filter(x=>x.status===200).length===1,{statuses:race.map(x=>x.status),finalBody:after.body});
 // Only after board CAS outcome: reuse Git's native fast-forward atomicity.
 const master=ok(await get('master-ref',apiRoot+'/git/ref/heads/master')),baseCommit=ok(await get('master-commit',apiRoot+'/git/commits/'+master.object.sha)),leaseBranch=`lab/d-claim-${stamp}`,leaseRef=apiRoot+'/git/refs/heads/'+leaseBranch;branches.push(leaseBranch);
 ok(await api('lease-ref-create','POST',apiRoot+'/git/refs',{ref:'refs/heads/'+leaseBranch,sha:master.object.sha}));
 async function proposal(label,parent,record){return ok(await api(label,'POST',apiRoot+'/git/commits',{message:JSON.stringify({schema:1,repository,issue:claimIssue.number,...record}),tree:baseCommit.tree.sha,parents:[parent]}));}
 const expiry=Date.now()+10000,proposals=await Promise.all(['actor-a','actor-b'].map(owner=>proposal('lease-propose-'+owner,master.object.sha,{owner,epoch:1,event:'claim-once',expiresAt:expiry})));
 const claimed=await Promise.all(proposals.map((p,i)=>api('lease-claim-'+i,'PATCH',leaseRef,{sha:p.sha,force:false})));const winnerIndex=claimed.findIndex(x=>x.status===200);assert(winnerIndex>=0);const winner=proposals[winnerIndex];add('native Git ref admits exactly one concurrent claim',claimed.filter(x=>x.status===200).length===1,{statuses:claimed.map(x=>x.status),winner:winner.sha});
 const leaseTip=ok(await get('lease-tip',apiRoot+'/git/ref/heads/'+leaseBranch));assert.equal(leaseTip.object.sha,winner.sha);const ownerRecord=JSON.parse(winner.message);ok(await api('publish-claim-reference','PATCH',apiRoot+`/issues/${claimIssue.number}`,{body:claimIssue.body+`\n\nSynthetic cooperative lease: ${leaseBranch} @ ${winner.sha}; owner ${ownerRecord.owner}; epoch1. Issue remains task authority; this ref is claim metadata, not a queue.`}));
 const replay=JSON.parse(ok(await get('replay-commit',apiRoot+'/git/commits/'+leaseTip.object.sha)).message);add('duplicate claim event does not create new commit',replay.event==='claim-once'&&leaseTip.object.sha===winner.sha,{method:'Read canonical current claim before replay; event history beyond this current lease unverified.'});
 // Crash is represented by owner process absence; wait for its actual wall-clock TTL.
 await new Promise(resolve=>setTimeout(resolve,Math.max(0,expiry-Date.now()+150)));
 const observedNow=Date.now();assert(observedNow>expiry);const successor=await proposal('lease-reclaim-proposal',winner.sha,{owner:'actor-recovery',epoch:2,event:'reclaim-after-crash',expiresAt:observedNow+600000});ok(await api('lease-reclaim','PATCH',leaseRef,{sha:successor.sha,force:false}));
 add('expired claim can be reclaimed without deleting ref',true,{expiredAt:expiry,reclaimedAfter:observedNow,epoch:2,qualification:'Cooperative client wall clock; server clock skew policy and hard authorization fencing unverified.'});
 const stale=await proposal('stale-owner-proposal',winner.sha,{owner:ownerRecord.owner,epoch:1,event:'late-completion',expiresAt:observedNow+600000});const staleUpdate=await api('stale-owner-update','PATCH',leaseRef,{sha:stale.sha,force:false});add('stale owner cannot advance canonical claim ref',staleUpdate.status===422||staleUpdate.status===409,{status:staleUpdate.status});
 const finalTip=ok(await get('lease-final-tip',apiRoot+'/git/ref/heads/'+leaseBranch));add('cooperative publish guard rejects stale fencing token',finalTip.object.sha!==winner.sha&&finalTip.object.sha===successor.sha,{qualification:'Read-check is not atomic with arbitrary external writes; privileged bypass remains possible.'});
 // Independent synthetic fixture repository; only its branches are published.
 const fixture=path.join(base,'fixture');mkdirSync(fixture);command('fixture-init',['init','-q'],fixture);command('identity-name',['config','user.name','Synthetic Lab'],fixture);command('identity-email',['config','user.email','lab@example.invalid'],fixture);
 writeFileSync(path.join(fixture,'counter.mjs'),'export function render(n) { return `Count: ${n}`; }\n');writeFileSync(path.join(fixture,'README.md'),'Synthetic D code fixture only.\n');command('seed-add',['add','.'],fixture);command('seed-commit',['commit','-qm','Synthetic counter baseline'],fixture);
 const fixtureBase=`lab/d-fixture-${stamp}`;branches.push(fixtureBase);command('seed-branch',['branch','-M',fixtureBase],fixture);command('seed-push',[...gitAuth,'push',`https://github.com/${repository}.git`,`${fixtureBase}:refs/heads/${fixtureBase}`],fixture);
 const work=[];for(const actor of ['a','b','external']){const branch=`lab/d-work-${actor}-${stamp}`,cwd=path.join(base,'work-'+actor);branches.push(branch);command('worktree-'+actor,['worktree','add','-b',branch,cwd,fixtureBase],fixture);work.push({actor,branch,cwd});snapshot(cwd,out+'/worktrees/'+actor+'-before.json');}
 writeFileSync(path.join(work[0].cwd,'counter.mjs'),'export function render(n) { if (!Number.isInteger(n) || n < 0) throw new TypeError("count"); return `Count: ${n}`; }\n');
 writeFileSync(path.join(work[1].cwd,'counter.mjs'),'export function render(n) { return `Total: ${n}`; }\n');
 writeFileSync(path.join(work[2].cwd,'README.md'),'Synthetic external contributor change while A/B work is active.\n');
 for(const w of work){command('add-'+w.actor,['add','.'],w.cwd);command('commit-'+w.actor,['commit','-qm','Synthetic actor '+w.actor],w.cwd);w.sha=command('sha-'+w.actor,['rev-parse','HEAD'],w.cwd).stdout.trim();command('push-'+w.actor,[...gitAuth,'push',`https://github.com/${repository}.git`,`${w.branch}:refs/heads/${w.branch}`],w.cwd);const pr=ok(await api('pr-'+w.actor,'POST',apiRoot+'/pulls',{title:`[synthetic D ${stamp}] actor ${w.actor}`,head:w.branch,base:fixtureBase,body:`Synthetic laboratory conflict/handoff fixture. Related task #${issues[w.actor==='b'?1:0].number}. Close after experiment; do not merge into master.`,draft:true}));prs.push({number:pr.number,url:pr.html_url,actor:w.actor});save();snapshot(w.cwd,out+'/worktrees/'+w.actor+'-after.json');}
 add('each task executes in separate branch and worktree',new Set(work.map(x=>x.cwd)).size===3&&new Set(work.map(x=>x.branch)).size===3);
 const conflict=run('git',['merge-tree','--write-tree',work[0].sha,work[1].sha],fixture,out+'/git/conflict-before-merge.json');add('two PRs changing common line expose conflict before merge',conflict.exitCode===1&&conflict.stdout.includes('CONFLICT'));
 const external=ok(await get('external-pr-seen',apiRoot+'/pulls/'+prs[2].number));add('external PR is visible during active work',external.head.sha===work[2].sha&&external.state==='open');
 const feedback=ok(await api('review-feedback','POST',apiRoot+`/pulls/${prs[1].number}/reviews`,{event:'COMMENT',body:'Synthetic independent review: D-R1 requires Count, not Total. Return this task to rework. This is an explicit comment review; no own-PR REQUEST_CHANGES approval claim.'}));
 writeFileSync(path.join(work[1].cwd,'counter.mjs'),readFileSync(path.join(work[0].cwd,'counter.mjs')));command('rework-add',['add','counter.mjs'],work[1].cwd);command('rework-commit',['commit','-qm','Address synthetic review D-R1'],work[1].cwd);command('rework-push',[...gitAuth,'push',`https://github.com/${repository}.git`,`${work[1].branch}:refs/heads/${work[1].branch}`],work[1].cwd);
 add('review feedback produces a new corrective commit',feedback.state==='COMMENTED'&&command('rework-sha',['rev-parse','HEAD'],work[1].cwd).stdout.trim()!==work[1].sha,{formalIndependentAccountReview:false});
 const testFile=path.join(base,'acceptance.mjs');writeFileSync(testFile,'import assert from "node:assert/strict"; const {render}=await import(process.argv[2]); assert.equal(render(0),"Count: 0"); assert.equal(render(3),"Count: 3"); for(const n of [-1,1.2,"1"])assert.throws(()=>render(n),TypeError); console.log("PASS D-R1 D-R2 D-R3");\n');
 const codeUrl=new URL('file:///'+path.join(work[1].cwd,'counter.mjs').replaceAll('\\','/')).href;const acceptance=run(process.execPath,[testFile,codeUrl],base,out+'/acceptance.json');add('reworked feature passes requirement-linked fresh-process tests',acceptance.exitCode===0);
 const handoff={feature:'d-counter-'+stamp,requirements:['D-R1','D-R2','D-R3'],issue:issues[1].number,pr:prs[1].number,branch:work[1].branch,commit:command('handoff-sha',['rev-parse','HEAD'],work[1].cwd).stdout.trim(),leaseRef:leaseBranch,leaseCommit:successor.sha,nextAction:'Inspect board blockers and PR feedback before selecting more work',providerStart:'Claude-shaped synthetic record',providerContinue:'Codex-shaped synthetic reader',actualNativeModelHandoff:false};json(out+'/handoff.json',handoff);writeFileSync(path.join(base,'handoff.json'),JSON.stringify(handoff));
 const resume=run(process.execPath,['-e','const fs=require("fs"); const x=JSON.parse(fs.readFileSync(process.argv[1])); if(!x.issue||!x.commit||!x.leaseCommit)process.exit(1); console.log(JSON.stringify(x));',path.join(base,'handoff.json')],base,out+'/restart-read.json');add('fresh process reconstructs explainable handoff state',resume.exitCode===0,{actualClaudeToCodexModelExecution:false});
 ok(await api('complete-blocker','PATCH',apiRoot+`/issues/${issues[0].number}`,{state:'closed'}));const afterBlocker=ok(await get('blocker-after-completion',apiRoot+`/issues/${issues[1].number}/dependencies/blocked_by`));add('blocker readiness follows real issue state',afterBlocker.length===1&&afterBlocker[0].id===issues[0].id&&afterBlocker[0].state==='closed');
 save();
}finally{
 const cleanup=[];for(const pr of prs){const r=await api('close-pr-'+pr.number,'PATCH',apiRoot+'/pulls/'+pr.number,{state:'closed'});cleanup.push({kind:'pr',number:pr.number,status:r.status});}
 for(const issue of issues){const r=await api('close-issue-'+issue.number,'PATCH',apiRoot+'/issues/'+issue.number,{state:'closed'});cleanup.push({kind:'issue',number:issue.number,status:r.status});}
 const verified=[];for(const x of cleanup){const r=await get('verify-closed-'+x.kind+'-'+x.number,apiRoot+'/'+(x.kind==='pr'?'pulls':'issues')+'/'+x.number);verified.push({...x,closed:r.status===200&&r.data.state==='closed'});}json(out+'/cleanup.json',{verified,allClosed:verified.every(x=>x.closed),retainedSyntheticBranches:branches,reason:'Retained for reproducible commit/ref evidence; no branch merged into master.'});save();
}
console.log(JSON.stringify(checks));
