import {readFileSync,readdirSync,statSync} from 'node:fs';
import {json} from './lab-evidence.mjs';
const base='spikes/e-memory',read=p=>JSON.parse(readFileSync(base+'/evidence/'+p,'utf8'));
const ledger=[],add=(scenario,value,evidence,note)=>ledger.push({scenario,status:value==null?'unverified':value?'passed':'failed',evidence,note});
for(const c of read('basic/result.json').checks)add('Basic: '+c.name,c.name==='native diagnostics redacts synthetic config key'?null:c.passed,'basic/result.json',c.name==='native diagnostics redacts synthetic config key'?'Raw false retained: collector incorrectly expected a retained key; native source drops it. No captured loaded-input bytes; exact canary ingestion remains unverified.':c.detail);
add('Basic diagnostics has no synthetic config canary exposure',!JSON.stringify(read('basic/native-diagnostics.json')).includes('SYNTHETIC_CONFIG_CANARY'),'basic/native-diagnostics.json','Observed output absence; not a generic redaction benchmark.');
const upgrade=read('basic-upgrade/result.json');for(const k of ['currentVersionVerified','upgradePreservedNote','uninstallRemovedEntrypoint','uninstallPreservedData','reinstallReadsData'])add('Basic lifecycle: '+k,upgrade[k],'basic-upgrade/result.json');
const concurrency=read('basic-concurrency/result.json');for(const r of concurrency.rounds){add('Basic same-note round '+r.round+' all appends acknowledged',r.acknowledged.length===2,'basic-concurrency/result.json');add('Basic same-note round '+r.round+' preserves acknowledged markers',r.lostAcknowledgedMarkers.length===0,'basic-concurrency/result.json','Bounded final MCP observations, not proof of permanent durable loss.');add('Basic same-note round '+r.round+' readers agree',!r.readersDisagree,'basic-concurrency/result.json');add('Basic same-note round '+r.round+' projection converges',r.seedProjection.converged&&r.finalProjection.converged,'basic-concurrency/result.json');add('Basic distinct-note controls round '+r.round,r.distinctControls.every(x=>x.acknowledged&&x.readable),'basic-concurrency/result.json');add('Basic distinct-note projections round '+r.round,r.distinctControls.every(x=>x.projection?.converged===true),'basic-concurrency/result.json');}
const ref=read('reference/result.json');for(const k of ['repeatedEntityCreationAddsNone','restartExact','explicitSeparatePathIsolated','sameAbsolutePathDifferentCheckoutShared','exportImportExact'])add('Reference: '+k,ref[k],'reference/result.json');
for(const q of ref.queries)add('Reference literal retrieval: '+q.query,q.precision===1&&q.recall===1,'reference/result.json',{bytes:q.bytes,corpus:'Three synthetic entities; not semantic retrieval.'});
add('Reference default isolates different working directories',!ref.defaultPathSharedAcrossCwd,'reference/result.json');add('Reference wrong path cannot expose another project',!ref.wrongProjectPathLeaks,'reference/result.json','File selection is not authorization.');add('Reference automatically redacts supplied canary',!ref.canaryStoredUnredacted,'reference/result.json');add('Reference handshake reports package version',ref.handshakeReportsPackageVersion,'reference/result.json');
for(const [group,value]of Object.entries({corruption:ref.corruption,deletion:ref.deletion}))for(const [key,passed]of Object.entries(value))add('Reference '+group+': '+key,passed,'reference/result.json');
for(const r of ref.concurrentWriters)add('Reference concurrent round '+r.round+' retains acknowledged writes',r.lostAcknowledgedWrites===0,'reference/result.json',{acknowledged:r.acknowledged,lost:r.lostAcknowledgedWrites,writeErrors:r.writeErrors});
add('Reference package uninstall preserves explicit external data',ref.packageRemoval.externalDataPreserved,'reference/result.json');add('Reference package uninstall preserves default data',!ref.packageRemoval.defaultPackageLocalDataRemoved,'reference/result.json');add('Reference package entrypoint removed',ref.packageRemoval.entryRemoved,'reference/result.json');
const native=read('reference/native-registration.json');add('Reference native Claude/Codex registration/removal',native.registrationAndRemovalPassed??null,'reference/native-registration.json');
for(const r of read('native-wiring/result.json')){const label=r.provider+' '+r.order,where='native-wiring/'+r.provider+'-'+r.order;
 for(const k of ['rigDryExit','rigUpgradeExit','nativeGetAfterRigExit','nativeRemovalExit','survivingRigExit'])add(label+' '+k,r[k]===0,where);
 for(const k of ['dryReadOnly','sharedEditsPreserved','deletedRigFilePreserved','nativeConfigPreservedByRig','dataSurvivesNativeRemoval'])add(label+' '+k,r[k],where);
 add(label+' native registration removed',r.getAfterRemovalExit!==0,where);add(label+' Rig files survive native removal',r.rigFilesChangedByNativeRemoval.length===0,where);
 const repeated=read(where+'/native-repeat.json');add(label+' native repeat preserves config',repeated.configByteIdentical&&repeated.getAfterRepeatExit===0,where+'/native-repeat.json',{exitCode:repeated.exitCode});
}
add('Basic handshake reports package version',read('basic/client-a-initialize.json').serverInfo.version==='0.23.2','basic/client-a-initialize.json');
for(const name of ['Native Claude auto-memory extraction/recall','Native Codex memory extraction/recall','Existing custom Memory implementation behavior','Private custom Memory data migration','Authorization against a hostile same-OS-user process','Semantic/embedding retrieval quality','Abrupt power-loss durability','Fully hash-locked cold offline dependency bootstrap','Reference cross-version server data migration','Reference exact Rig installation-order matrix','Automatic recovery without an explicit backup','Basic package redistribution approval','Reference missing packaged license clearance'])add(name,null,'report.md');
json(base+'/scenario-ledger.json',ledger);json(base+'/result.json',{spike:'E',verdict:'ADAPT',confidence:'medium',candidate:'Native harness memory by default; optional Basic Memory local MCP; reject reference graph for shared concurrent writes',version:'Basic Memory0.23.2 @ c0bd87c6d5a4a58034b1d6c8c5018e443b0bd048; reference2026.8.31 @ a40bc270fb5ece62673f8a1196f57116d885c5eb',rigBaseline:'0.9.0',scenariosPassed:ledger.filter(x=>x.status==='passed').length,scenariosFailed:ledger.filter(x=>x.status==='failed').length,scenariosUnverified:ledger.filter(x=>x.status==='unverified').length,estimatedIntegrationDays:3,estimatedAnnualMaintenanceDays:3,qualification:'No custom memory engine justified. Optional Basic Memory remains bounded by observed concurrency/project-routing results and AGPL distribution decision; no unconditional native recall or migration claim.'});
console.log(JSON.stringify(ledger.reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{})));
let commands=0,snapshots=0;const nonzero=[];
function inspect(v,p){if(!v||typeof v!=='object')return;if(Array.isArray(v.command)&&Object.hasOwn(v,'exitCode')){commands++;if(v.exitCode!==0)nonzero.push({file:p,exitCode:v.exitCode,output:((v.stdout||'')+(v.stderr||'')).slice(0,400)});}if(v.files&&v.gitStatus&&typeof v.gitStatus==='object')snapshots++;for(const [k,x]of Object.entries(v))inspect(x,p+':'+k);}
function walk(p){for(const n of readdirSync(p)){if(n==='windows-local')continue;const f=p+'/'+n;if(statSync(f).isDirectory())walk(f);else if(f.endsWith('.json'))inspect(JSON.parse(readFileSync(f,'utf8')),f);}}
for(const dir of ['basic-setup','basic','basic-concurrency','basic-upgrade','reference','native-wiring'])walk(base+'/evidence/'+dir);
json(base+'/measurements.json',{checkedAt:'2026-09-14',canonicalRun:'https://github.com/serhii-baksheiev/agent-stack-lab/actions/runs/34839170081',scenarioSha:read('basic/result.json').scenarioSha,commands,snapshots,nonzero,basicStress:{acknowledged:concurrency.totalAcknowledgedAppends,missingAtFinalObservation:concurrency.totalLostAcknowledgedMarkers,projectionTimeouts:concurrency.projectionTimeouts,readerDisagreements:concurrency.roundsWithReaderDisagreement,distinctControlsPass:concurrency.allDistinctControlsPass},referenceStress:ref.concurrentWriters,qualification:'Only canonical Linux folders counted; separate Windows/failed-run diagnostics excluded. No native model recall or semantic benchmark.'});
const dimensions=['userUtility','maturity','maintainability','upstreamActivity','claudeCompatibility','codexCompatibility','reproducibility','upgradeUninstall','absenceOfFileConflicts','teamwork','boardIntegration','security','offlineLocalFirst','integrationCost','annualMaintenanceCost','lowVendorLockIn','licenseSuitability'];
const rows=[['Basic Memory 0.23.2',[7,7,6,9,7,7,6,7,8,6,0,6,8,6,6,8,4],'Actual MCP/storage/lifecycle and both Rig orders; native inference unverified; AGPL distribution conditional.'],['Reference memory 2026.8.31',[4,5,6,8,7,7,8,3,6,1,0,3,8,8,6,9,3],'Actual MCP/native registration; lost concurrent updates, default package-local data loss; cross-version upgrade and licensing clearance unverified.'],['Native Claude/Codex memory',[0,0,8,9,0,0,0,0,8,0,0,0,0,9,9,3,5],'Documented native memory and feature metadata only; recall not measured. Default is a simplicity policy, not benchmark superiority.'],['Custom Memory public contract',[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],'No implementation or public contract beyond requested scenarios available; no measured advantage.']];
json(base+'/scores.json',{checkedAt:'2026-09-14',scale:'0 worst, 10 best; high cost/lock-in scores mean lower cost/lock-in. Zero with unverified status is a numeric placeholder, not measured inferiority; do not average.',basis:'Engineering judgments in this bounded synthetic scope; not measured product quality.',candidates:rows.map(([candidate,scores,evidence])=>({candidate,confidence:'medium',dimensions:Object.fromEntries(dimensions.map((d,i)=>[d,{score:scores[i],status:scores[i]===0?'unverified':'engineering-judgment',evidence}]))}))});
