import {readFileSync,readdirSync,statSync} from 'node:fs';
import {json} from './lab-evidence.mjs';
const base='spikes/d-team-orchestration',read=p=>JSON.parse(readFileSync(base+'/evidence/'+p,'utf8')),board=read('board/result.json'),ready=read('orchestrators/result.json'),ledger=[];
const add=(scenario,value,evidence,note)=>ledger.push({scenario,status:value==null?'unverified':value?'passed':'failed',evidence,note});
for(const c of board.checks)add(c.name==='real blocker links prevent selecting blocked task'?'Real blocker API exposes task readiness':c.name,c.passed,'board/result.json',c.detail);
for(const c of ready.checks)add(c.name,c.passed,'orchestrators/result.json',c.qualification);
add('All synthetic board issues and PRs closed',read('board/cleanup.json').allClosed,'board/cleanup.json');
for(const name of [...new Set([...ready.unverified,'Two autonomous native models choose next issue','Native Claude-to-Codex implementation continuation','Native compaction/restart of team execution','Jira or other board transition CAS','Historical event replay and exactly-once task creation','Server-clock/clock-skew-safe lease expiry','Hard atomic publication fencing','Complete Rig overlap orders for ready orchestrator installations'])])add(name,null,'report.md');
json(base+'/scenario-ledger.json',ledger);json(base+'/result.json',{spike:'D',verdict:'ADAPT',confidence:'medium',candidate:'Native agents + external board + thin task/handoff skill; optional claim layer remains conditional, no Rig scheduler',version:'GitHub API2026-03-10; Symphony0.0.2; OpenHands Canvas1.18.0 / Automation1.11.1; Claude2.1.270 / Codex0.154.0',rigBaseline:'0.9.0',scenariosPassed:ledger.filter(x=>x.status==='passed').length,scenariosFailed:ledger.filter(x=>x.status==='failed').length,scenariosUnverified:ledger.filter(x=>x.status==='unverified').length,estimatedIntegrationDays:3,estimatedAnnualMaintenanceDays:3,qualification:'Primitive/source/unit observations, not a qualified end-to-end autonomous team. Optional production claim adapter estimated5–8 additional days,3–5 annual; no queue/framework built.'});
let commands=0,snapshots=0,apiCalls=0;const nonzero=[];
function inspect(v,p){if(!v||typeof v!=='object')return;if(Array.isArray(v.command)&&Object.hasOwn(v,'exitCode')){commands++;if(v.exitCode!==0)nonzero.push({file:p,exitCode:v.exitCode});}if(v.method&&v.endpoint&&v.responseHeaders){apiCalls++;if(v.status>=400)nonzero.push({file:p,status:v.status,message:v.data?.message});}if(v.files&&v.gitStatus&&typeof v.gitStatus==='object')snapshots++;for(const [k,x]of Object.entries(v))inspect(x,p+':'+k);}
function walk(p){for(const n of readdirSync(p)){const f=p+'/'+n;if(statSync(f).isDirectory())walk(f);else if(f.endsWith('.json'))inspect(JSON.parse(readFileSync(f,'utf8')),f);}}
for(const dir of ['board','orchestrators'])walk(base+'/evidence/'+dir);
json(base+'/measurements.json',{checkedAt:'2026-09-14',boardScenarioSha:board.scenarioSha,orchestratorScenarioSha:ready.scenarioSha,canonicalOrchestratorRun:'https://github.com/serhii-baksheiev/agent-stack-lab/actions/runs/34841316242',commands,snapshots,apiCalls,nonzero,qualification:'Board actual API/worktrees and ready source/unit tests counted separately; Windows source discovery excluded.'});
const dims=['userUtility','maturity','maintainability','upstreamActivity','claudeCompatibility','codexCompatibility','reproducibility','upgradeUninstall','absenceOfFileConflicts','teamwork','boardIntegration','security','offlineLocalFirst','integrationCost','annualMaintenanceCost','lowVendorLockIn','licenseSuitability'];
const rows=[['Native teams/subagents',[7,7,9,9,7,7,6,8,8,7,0,6,4,9,9,4,5],'Current official docs/pinned source; actual harness team execution and distributed ownership unverified.'],['GitHub Issues/PRs API2026-03-10',[8,9,9,9,8,8,7,8,9,7,9,7,2,8,8,5,6],'Actual links/PRs/conflicts; Issue conditional PATCH400. Generic CLI access, not native model integration.'],['Symphony0.0.2',[7,5,6,8,0,7,7,0,0,6,7,5,3,5,5,7,9],'Pinned upstream runtime tests with memory tracker; single supervised controller; lifecycle/deployment not qualified.'],['OpenHands Canvas1.18/Automation1.11.1',[7,7,6,9,0,0,7,0,0,7,0,6,6,4,4,8,10],'Native launcher metadata + native scheduler query tests; complete backend/provider/board lifecycle unverified.'],['Jira',[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],'No Jira mutation authorized outside lab; no tested task/claim integration.'],['Cooperative Git-ref claim proof',[5,2,5,0,0,0,7,0,8,5,5,3,2,5,4,8,0],'Lab-only native fast-forward primitive; no production package, hard fencing, historical idempotence or universal queue.']];
json(base+'/scores.json',{checkedAt:'2026-09-14',scale:'0 worst10 best; high cost/lock-in means lower cost/lock-in. Unverified zero is numeric placeholder, not measured inferiority; do not average.',basis:'Engineering judgments in bounded evidence scope.',candidates:rows.map(([candidate,scores,evidence])=>({candidate,confidence:'medium',dimensions:Object.fromEntries(dims.map((d,i)=>[d,{score:scores[i],status:scores[i]===0?'unverified':'engineering-judgment',evidence}]))}))});
console.log(JSON.stringify({commands,snapshots,apiCalls,passed:ledger.filter(x=>x.status==='passed').length,failed:ledger.filter(x=>x.status==='failed').length,unverified:ledger.filter(x=>x.status==='unverified').length}));
