import {readFileSync,writeFileSync} from 'node:fs';
import {json} from './lab-evidence.mjs';
const base='spikes/a-spec-kit-manifest',e=base+'/evidence';
const read=p=>JSON.parse(readFileSync(e+'/'+p,'utf8').replace(/^\uFEFF/,''));
const ledger=[];
const add=(scenario,pass,evidence,note)=>ledger.push({scenario,status:pass===null?'unverified':pass?'passed':'failed',evidence,note});
for(const r of read('integration/results.json')) {
 const ref='integration/'+r.order;
 add(r.order+': first and second installs',r.firstExit===0&&r.secondExit===0,ref);
 add(r.order+': repeat init refuses existing Rig',r.rigRepeatInitExit===1,ref);
 add(r.order+': Rig dry-run read-only',r.rigDryExit===0&&r.dryReadOnly,ref);
 add(r.order+': user edits retained',r.editsPreserved,ref);
 add(r.order+': Rig deliberate deletion retained',r.deletedStaysRemoved,ref);
 add(r.order+': Spec Kit deliberate deletion retained',r.specDeletedStaysRemoved,ref,'Required Rig property; upstream deliberately recreates missing managed skill.');
 add(r.order+': Spec Kit modified upgrade refuses',r.specEditedUpgradeExit===1,ref);
 add(r.order+': Spec uninstall retains Rig bytes',r.specUninstallExit===0&&r.rigSurvivesSpecUninstall,ref);
 add(r.order+': Spec uninstall retains edited skill',r.editedSpecSkillSurvives,ref);
 add(r.order+': repeat init then Claude uninstall retains Codex registration',r.specSurvivingCodexStatusExit===0,ref,'Observed missing integration state; preferred upgrade path tested separately.');
 add(r.order+': modified wiring blocks Rig removal prototype',r.rigUninstallBlockedOnModifiedWiring,ref);
 add(r.order+': no natural second-component overwrite',r.naturalSecondComponentOverwrites.length===0,ref,'Ubuntu core install only; see Windows wiring separately.');
}
const offline=read('offline/result.json');
add('Offline warmed-cache two-install replay',offline.fileCounts.length===2&&offline.fileCounts.every(n=>n===120),'offline/result.json');
add('Offline full byte reproducibility',offline.byteIdentical,'offline/result.json');
const upgrade=read('release-upgrade/result.json');
const multi=read('multi-provider/result.json');add('Native upgrade then Claude uninstall retains Codex registration',multi.statusExit===0&&multi.codexRemainsRegistered,'multi-provider/result.json');
add('Spec Kit actual 1.0.5 to 1.0.6 upgrade',upgrade.upgradeExit===0&&upgrade.statusExit===0&&upgrade.constitutionPreserved,'release-upgrade/result.json');
const collision=read('collisions/results.json');
for(const r of collision.filter(r=>r.scenario==='individual-preexisting-collision')) add(`${r.tool}: retain preexisting ${r.file}`,r.preserved,'collisions/individual-results.json',r.tool==='spec-kit'?'Explicit --force bootstrap, not manifest-aware upgrade.':undefined);
const uninstall=collision.find(r=>r.scenario==='bounded-rig-uninstall');
add('Bounded Rig removal preserves Spec Kit',uninstall?.removed===83&&uninstall.specCliStatusExit===0,'collisions/uninstall');
const feature=read('collisions/uninstall/survivor-feature.json');add('Upstream feature script executes after Rig removal',feature.exitCode===0,'collisions/uninstall/survivor-feature.json');
const windows=read('windows-wiring/results.json');
for(const r of windows) add('Windows '+r.order+': Rig retains exact settings ownership',r.rigOwnsExactBytes,'windows-wiring/results.json','Semantic-equivalent CRLF still violates byte identity.');
add('Windows bounded newline-only repair restores ownership',windows.every(r=>r.afterBoundedRepairRigOwnsExactBytes),'windows-wiring/results.json');
for(const [scenario,note] of [['Live Claude and Codex workflow execution','Covered later in B; files/status are not model execution.'],['All optional Spec Kit extension ownership','Core only; agent-context and events extensions need separate qualification.'],['Uncached offline bootstrap with hash-pinned Python closure','Warm cache and resolved dependencies are recorded; closure not distributed.'],['Native complete Rig uninstall','CLI has no uninstall; tested operation is a bounded lab adapter.'],['Exhaustive malicious path/symlink tests','Guard implementation inspected, not a complete security certification.']]) add(scenario,null,'report.md',note);
json(base+'/scenario-ledger.json',ledger);
json(base+'/result.json',{spike:'A',verdict:'ADAPT',confidence:'medium',candidate:'GitHub Spec Kit',version:'1.0.6',commit:'96c9bd657bfd5de0d651a6165084932b7304ac99',rigBaseline:'0.9.0',qualification:'conditional: Linux core lifecycle; Windows settings ownership conflict',scenariosPassed:ledger.filter(x=>x.status==='passed').length,scenariosFailed:ledger.filter(x=>x.status==='failed').length,scenariosUnverified:ledger.filter(x=>x.status==='unverified').length,estimatedIntegrationDays:3,estimatedAnnualMaintenanceDays:3,estimateRangeDays:[2,4],ledger:'scenario-ledger.json'});
const rows=collision.filter(r=>r.scenario==='individual-preexisting-collision');
writeFileSync(base+'/conflict-matrix.md','# Exact-path collision matrix\n\nUbuntu observed `init` behavior. Spec Kit uses explicit `--force`; these outcomes do not describe its safer manifest-aware upgrade.\n\n| Tool | Seeded path | Exit | Bytes retained |\n| --- | --- | --- | --- |\n'+rows.map(r=>`| ${r.tool} | \`${r.file}\` | ${r.exitCode} | ${r.preserved} |`).join('\n')+'\n\nWindows Rig-first then Spec Kit rewrites settings line endings and loses exact manifest ownership; see evidence/windows-wiring/results.json.\n');
console.log(JSON.stringify(JSON.parse(readFileSync(base+'/result.json')),null,2));
